[default]
spriteMultiplicity = 1
size = 0.5
speed = 6
turningSpeed = 4
sight = 0.5
unarmedAttackSize = 0.5
hpRegenRate = 1000
behavior = "meleeAttack"
inventory = []

[player]
spritePos = [4, 3]
hp = 100
strength = 10
defense = 5

[gunman]
spritePos = [4, 3]
hp = 60
strength = 10
defense = 5
behavior = "rangedAttack"
inventory = ["handgun"]

[zombie]
spritePos = [0, 6]
spriteMultiplicity = 10
hp = [30, 60]
strength = [5, 12]
defense = [0, 7]
speed = [1, 2]

[thief]
spritePos = [6, 2]
hp = [60, 90]
strength = [5, 12]
defense = [3, 7]
speed = [5, 6]
behavior = "thief"
